version: 0.1
os: linux
files:
  - source: target/simple-web-app.war
    destination: /usr/share/tomcat7/webapps
hooks:
  ApplicationStart:
    - location: restart.sh    
      timeout: 300
      runas: root
